# Site settings
name: 知行合一
email: 495244854@qq.com
author: Cristo Geng
url: http://www.glphp.com
#resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/albaba1903/
baseurl: ""
description: 理想不是靠空谈的，是靠格物致知。靠实践，靠自省 ，即“知行合一”!
meta_description: 耿明;个人博客;天理不是靠空谈的，是靠格物致知。靠实践，靠自省 ，即“知行合一”
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: albaba1903
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : luoyan35714
    disqus :
        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light